FROM python:3.7-slim
 	 
RUN mkdir /app
 	 
COPY requirements.txt /app
 	 
RUN pip3 install -r /app/requirements.txt --no-cache-dir
 	 
COPY . /app
 	 
WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . .